# serverless.yml

service: proy-invrtir-grafico

provider:
  name: aws
  runtime: nodejs14.x
  stage: proy
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /